default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: haikouille_development

test:
  <<: *default
  database: haikouille_test

production:
  <<: *default
  database: haikouille_production
  username: haikouille
  password: <%= ENV['HAIKOUILLE_DATABASE_PASSWORD'] %>
